package home

import (
	"fmt"
	"os"
	"path/filepath"

	// Embed small offline fixtures so go-install users get a first-run win.
	_ "embed"
)

//go:embed fixtures/brainyard-session.jsonl
var fixtureBrainyard []byte

//go:embed fixtures/acp-session.jsonl
var fixtureACP []byte

// OfflineDemo describes a bundled no-network experience.
type OfflineDemo struct {
	ID       string
	Title    string
	Dialect  string
	Fixture  []byte
	Filename string
}

// OfflineDemos are available from the home hub without a clone or network.
func OfflineDemos() []OfflineDemo {
	return []OfflineDemo{
		{
			ID:       "brainyard",
			Title:    "Multi-agent timeline fixture",
			Dialect:  "brainyard",
			Fixture:  fixtureBrainyard,
			Filename: "brainyard-session.jsonl",
		},
		{
			ID:       "acp",
			Title:    "ACP session fixture",
			Dialect:  "acp",
			Fixture:  fixtureACP,
			Filename: "acp-session.jsonl",
		},
	}
}

// MaterializeDemo writes the fixture under dir and returns a temporary
// replay run-config path that points at it.
func MaterializeDemo(dir string, demo OfflineDemo) (configPath string, err error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create demo dir: %w", err)
	}
	fixturePath := filepath.Join(dir, demo.Filename)
	if err := os.WriteFile(fixturePath, demo.Fixture, 0o600); err != nil {
		return "", fmt.Errorf("write fixture: %w", err)
	}
	cfgPath := filepath.Join(dir, demo.ID+"-demo.yaml")
	contents := fmt.Sprintf(`# Offline demo — generated by agent-stream-dbg home hub
transport:
  type: replay
  base_url: %q
dialect:
  file: %q
session:
  auto_setup: false
logging:
  dir: %q
`, fixturePath, demo.Dialect, filepath.Join(dir, "logs"))
	if err := os.WriteFile(cfgPath, []byte(contents), 0o600); err != nil {
		return "", fmt.Errorf("write demo config: %w", err)
	}
	return cfgPath, nil
}
