// Test service for the gRPC transport's A2A cross-transport parity test
// (dialects/cross_transport_test.go's TestA2ADialect_CrossTransportParity)
// — the gRPC equivalent of testdata/fixtures/a2a-session.jsonl for SSE.
//
// Vendored from the real A2A (Agent2Agent) protocol's normative proto —
// https://github.com/a2aproject/A2A/blob/main/specification/a2a.proto
// (Apache License 2.0: https://github.com/a2aproject/A2A/blob/main/LICENSE)
// — fetched fresh 2026-07-15, matching the same commit dialects/a2a.yaml's
// own header comment verified its field names/enum strings against. Every
// field number, field name, and enum value kept below is copied verbatim
// from that source; nothing is invented. Line numbers in the comments on
// each message refer to that source file as fetched on 2026-07-15.
//
// Trimmed, deliberately, to only what this one parity test needs — not an
// approximation of the fields that ARE kept, only a subset of which
// fields/oneof branches are present at all:
//
//   - StreamResponse's oneof (a2a.proto:790-802) keeps its real task=1,
//     status_update=3, artifact_update=4 field numbers and names, but
//     drops the real message=2 branch (type Message) entirely: this
//     test's two sub-cases are statusUpdate and artifactUpdate (mirroring
//     dialects/cross_transport_test.go's cross-transport parity test's
//     two sub-cases) — a2a.yaml's `message` rule is already proven over
//     SSE by dialects/dialects_test.go's TestA2ADialect_ExactDecode; this
//     file's job is the gRPC transport seam, not re-proving every dialect
//     rule a second time. Message itself is therefore not vendored here,
//     and Task.history (repeated Message, a2a.proto:180) and
//     TaskStatus.message (Message, a2a.proto:215) — both real fields —
//     are dropped for the same reason.
//   - Task, TaskStatusUpdateEvent, TaskArtifactUpdateEvent, TaskStatus,
//     Artifact, and Part each keep every field dialects/a2a.yaml's rules
//     actually read (see that file's per-rule comments) plus the
//     surrounding fields needed for a structurally faithful message, and
//     drop the rest. Notably dropped throughout: every message's
//     `metadata` field (google.protobuf.Struct) and TaskStatus's
//     `timestamp` (google.protobuf.Timestamp) — real fields on the real
//     messages, but pulling in google/protobuf/struct.proto and
//     timestamp.proto imports for fields no rule in a2a.yaml reads is
//     unjustified complexity for this test's scope (a legitimate choice
//     the task explicitly leaves open either way). Part's oneof keeps
//     only its `text` member (a2a.yaml's artifactUpdate rule extracts
//     parts.0.text specifically; raw/url/data are unmapped in the
//     dialect itself, per its own comment, so there is nothing for a
//     parity test to exercise on those branches).
//   - The google.api.field_behavior REQUIRED annotations on the real
//     proto's fields are represented here only as "// REQUIRED" text
//     comments (matching the real proto's own doc comments), not the
//     actual (google.api.field_behavior) option — that avoids importing
//     google/api/field_behavior.proto for an annotation this test never
//     inspects at runtime.
//
// package is a2a.v1, not the real proto's lf.a2a.v1: this is a
// deliberately trimmed test-only vendor, not a byte-for-byte mirror of
// the upstream package, and a distinct package name avoids any
// impression that github.com/lancekrogers/stream-debugger's generated Go
// package is (or could be mistaken for) the real upstream one. The RPC
// name SendStreamingMessage and its request/response shapes are kept
// faithful to the real spec (a2a.proto:31-42) wherever vendored.
//
// A2AService itself is trimmed to this one RPC — the real service
// (a2a.proto:19-165) has 11 methods (SendMessage, GetTask, CancelTask,
// ...); only SendStreamingMessage, the RPC dialects/a2a.yaml's rules
// decode responses from, is needed to exercise the gRPC transport seam.
// Mirrors testdata/proto/agentstream.proto's own posture: a minimal
// service, not a full second real dialect.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: a2a.proto

package a2apb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	A2AService_SendStreamingMessage_FullMethodName = "/a2a.v1.A2AService/SendStreamingMessage"
)

// A2AServiceClient is the client API for A2AService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A2AService (a2a.proto:19-165), trimmed to its one streaming RPC — see
// the file header for why the other 10 methods aren't vendored.
type A2AServiceClient interface {
	// SendStreamingMessage (a2a.proto:31-42): sends a streaming message to
	// an agent, allowing for real-time interaction and status updates.
	SendStreamingMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
}

type a2AServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewA2AServiceClient(cc grpc.ClientConnInterface) A2AServiceClient {
	return &a2AServiceClient{cc}
}

func (c *a2AServiceClient) SendStreamingMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &A2AService_ServiceDesc.Streams[0], A2AService_SendStreamingMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AService_SendStreamingMessageClient = grpc.ServerStreamingClient[StreamResponse]

// A2AServiceServer is the server API for A2AService service.
// All implementations must embed UnimplementedA2AServiceServer
// for forward compatibility.
//
// A2AService (a2a.proto:19-165), trimmed to its one streaming RPC — see
// the file header for why the other 10 methods aren't vendored.
type A2AServiceServer interface {
	// SendStreamingMessage (a2a.proto:31-42): sends a streaming message to
	// an agent, allowing for real-time interaction and status updates.
	SendStreamingMessage(*SendMessageRequest, grpc.ServerStreamingServer[StreamResponse]) error
	mustEmbedUnimplementedA2AServiceServer()
}

// UnimplementedA2AServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedA2AServiceServer struct{}

func (UnimplementedA2AServiceServer) SendStreamingMessage(*SendMessageRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SendStreamingMessage not implemented")
}
func (UnimplementedA2AServiceServer) mustEmbedUnimplementedA2AServiceServer() {}
func (UnimplementedA2AServiceServer) testEmbeddedByValue()                    {}

// UnsafeA2AServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to A2AServiceServer will
// result in compilation errors.
type UnsafeA2AServiceServer interface {
	mustEmbedUnimplementedA2AServiceServer()
}

func RegisterA2AServiceServer(s grpc.ServiceRegistrar, srv A2AServiceServer) {
	// If the following call panics, it indicates UnimplementedA2AServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&A2AService_ServiceDesc, srv)
}

func _A2AService_SendStreamingMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(A2AServiceServer).SendStreamingMessage(m, &grpc.GenericServerStream[SendMessageRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AService_SendStreamingMessageServer = grpc.ServerStreamingServer[StreamResponse]

// A2AService_ServiceDesc is the grpc.ServiceDesc for A2AService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var A2AService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "a2a.v1.A2AService",
	HandlerType: (*A2AServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStreamingMessage",
			Handler:       _A2AService_SendStreamingMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "a2a.proto",
}
