// Test service for the gRPC transport's mock server — the gRPC equivalent
// of testdata/fixtures/brainyard-session.jsonl for SSE. Deliberately
// small: enough oneof case variety to prove discriminator inference,
// nothing resembling a second real dialect.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: agentstream.proto

package agentstreampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentStream_Stream_FullMethodName = "/agentstream.v1.AgentStream/Stream"
	AgentStream_Chat_FullMethodName   = "/agentstream.v1.AgentStream/Chat"
)

// AgentStreamClient is the client API for AgentStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentStream is a minimal multi-agent streaming service: one
// server-streaming RPC that replays a scripted sequence of StreamEvents,
// and one bidi RPC for interactive-input tests later in this phase.
type AgentStreamClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEvent], error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, StreamEvent], error)
}

type agentStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentStreamClient(cc grpc.ClientConnInterface) AgentStreamClient {
	return &agentStreamClient{cc}
}

func (c *agentStreamClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentStream_ServiceDesc.Streams[0], AgentStream_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_StreamClient = grpc.ServerStreamingClient[StreamEvent]

func (c *agentStreamClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, StreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentStream_ServiceDesc.Streams[1], AgentStream_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, StreamEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_ChatClient = grpc.BidiStreamingClient[ChatMessage, StreamEvent]

// AgentStreamServer is the server API for AgentStream service.
// All implementations must embed UnimplementedAgentStreamServer
// for forward compatibility.
//
// AgentStream is a minimal multi-agent streaming service: one
// server-streaming RPC that replays a scripted sequence of StreamEvents,
// and one bidi RPC for interactive-input tests later in this phase.
type AgentStreamServer interface {
	Stream(*StreamRequest, grpc.ServerStreamingServer[StreamEvent]) error
	Chat(grpc.BidiStreamingServer[ChatMessage, StreamEvent]) error
	mustEmbedUnimplementedAgentStreamServer()
}

// UnimplementedAgentStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentStreamServer struct{}

func (UnimplementedAgentStreamServer) Stream(*StreamRequest, grpc.ServerStreamingServer[StreamEvent]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentStreamServer) Chat(grpc.BidiStreamingServer[ChatMessage, StreamEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentStreamServer) mustEmbedUnimplementedAgentStreamServer() {}
func (UnimplementedAgentStreamServer) testEmbeddedByValue()                     {}

// UnsafeAgentStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentStreamServer will
// result in compilation errors.
type UnsafeAgentStreamServer interface {
	mustEmbedUnimplementedAgentStreamServer()
}

func RegisterAgentStreamServer(s grpc.ServiceRegistrar, srv AgentStreamServer) {
	// If the following call panics, it indicates UnimplementedAgentStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentStream_ServiceDesc, srv)
}

func _AgentStream_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentStreamServer).Stream(m, &grpc.GenericServerStream[StreamRequest, StreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_StreamServer = grpc.ServerStreamingServer[StreamEvent]

func _AgentStream_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentStreamServer).Chat(&grpc.GenericServerStream[ChatMessage, StreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_ChatServer = grpc.BidiStreamingServer[ChatMessage, StreamEvent]

// AgentStream_ServiceDesc is the grpc.ServiceDesc for AgentStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentstream.v1.AgentStream",
	HandlerType: (*AgentStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentStream_Stream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _AgentStream_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentstream.proto",
}
