// Test service for the gRPC transport's mock server — the gRPC equivalent
// of testdata/fixtures/brainyard-session.jsonl for SSE. Deliberately
// small: enough oneof case variety to prove discriminator inference,
// nothing resembling a second real dialect.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: agentstream.proto

package agentstreampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_agentstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_agentstream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_agentstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_agentstream_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// StreamEvent mirrors architecture.md's example shape: the oneof case
// name is what a discriminator: oneof config lifts into Frame.Name,
// exactly like an SSE event: line.
type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamEvent_SessionStart
	//	*StreamEvent_AgentContent
	//	*StreamEvent_ToolCall
	Payload       isStreamEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_agentstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agentstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_agentstream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamEvent) GetPayload() isStreamEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamEvent) GetSessionStart() *SessionStart {
	if x != nil {
		if x, ok := x.Payload.(*StreamEvent_SessionStart); ok {
			return x.SessionStart
		}
	}
	return nil
}

func (x *StreamEvent) GetAgentContent() *AgentContent {
	if x != nil {
		if x, ok := x.Payload.(*StreamEvent_AgentContent); ok {
			return x.AgentContent
		}
	}
	return nil
}

func (x *StreamEvent) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Payload.(*StreamEvent_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

type isStreamEvent_Payload interface {
	isStreamEvent_Payload()
}

type StreamEvent_SessionStart struct {
	SessionStart *SessionStart `protobuf:"bytes,1,opt,name=session_start,json=sessionStart,proto3,oneof"`
}

type StreamEvent_AgentContent struct {
	AgentContent *AgentContent `protobuf:"bytes,2,opt,name=agent_content,json=agentContent,proto3,oneof"`
}

type StreamEvent_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,3,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

func (*StreamEvent_SessionStart) isStreamEvent_Payload() {}

func (*StreamEvent_AgentContent) isStreamEvent_Payload() {}

func (*StreamEvent_ToolCall) isStreamEvent_Payload() {}

type SessionStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_agentstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_agentstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_agentstream_proto_rawDescGZIP(), []int{3}
}

func (x *SessionStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AgentContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sequence      int32                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentContent) Reset() {
	*x = AgentContent{}
	mi := &file_agentstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentContent) ProtoMessage() {}

func (x *AgentContent) ProtoReflect() protoreflect.Message {
	mi := &file_agentstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentContent.ProtoReflect.Descriptor instead.
func (*AgentContent) Descriptor() ([]byte, []int) {
	return file_agentstream_proto_rawDescGZIP(), []int{4}
}

func (x *AgentContent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentContent) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_agentstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_agentstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_agentstream_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// TypedEnvelope pairs a plain string type tag with a self-describing
// Any payload — the shape discriminator: field:type exists for
// (architecture.md: "field:type (a type string + google.protobuf.Any)").
type TypedEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedEnvelope) Reset() {
	*x = TypedEnvelope{}
	mi := &file_agentstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedEnvelope) ProtoMessage() {}

func (x *TypedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_agentstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedEnvelope.ProtoReflect.Descriptor instead.
func (*TypedEnvelope) Descriptor() ([]byte, []int) {
	return file_agentstream_proto_rawDescGZIP(), []int{6}
}

func (x *TypedEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypedEnvelope) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_agentstream_proto protoreflect.FileDescriptor

const file_agentstream_proto_rawDesc = "" +
	"\n" +
	"\x11agentstream.proto\x12\x0eagentstream.v1\x1a\x19google/protobuf/any.proto\"H\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xdb\x01\n" +
	"\vStreamEvent\x12C\n" +
	"\rsession_start\x18\x01 \x01(\v2\x1c.agentstream.v1.SessionStartH\x00R\fsessionStart\x12C\n" +
	"\ragent_content\x18\x02 \x01(\v2\x1c.agentstream.v1.AgentContentH\x00R\fagentContent\x127\n" +
	"\ttool_call\x18\x03 \x01(\v2\x18.agentstream.v1.ToolCallH\x00R\btoolCallB\t\n" +
	"\apayload\"-\n" +
	"\fSessionStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"_\n" +
	"\fAgentContent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x05R\bsequence\"`\n" +
	"\bToolCall\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"S\n" +
	"\rTypedEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload2\xea\x01\n" +
	"\vAgentStream\x12F\n" +
	"\x06Stream\x12\x1d.agentstream.v1.StreamRequest\x1a\x1b.agentstream.v1.StreamEvent0\x01\x12D\n" +
	"\x04Chat\x12\x1b.agentstream.v1.ChatMessage\x1a\x1b.agentstream.v1.StreamEvent(\x010\x01\x12M\n" +
	"\vStreamTyped\x12\x1d.agentstream.v1.StreamRequest\x1a\x1d.agentstream.v1.TypedEnvelope0\x01BRZPgithub.com/lancekrogers/stream-debugger/internal/testutil/mockgrpc/agentstreampbb\x06proto3"

var (
	file_agentstream_proto_rawDescOnce sync.Once
	file_agentstream_proto_rawDescData []byte
)

func file_agentstream_proto_rawDescGZIP() []byte {
	file_agentstream_proto_rawDescOnce.Do(func() {
		file_agentstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentstream_proto_rawDesc), len(file_agentstream_proto_rawDesc)))
	})
	return file_agentstream_proto_rawDescData
}

var file_agentstream_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agentstream_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: agentstream.v1.StreamRequest
	(*ChatMessage)(nil),   // 1: agentstream.v1.ChatMessage
	(*StreamEvent)(nil),   // 2: agentstream.v1.StreamEvent
	(*SessionStart)(nil),  // 3: agentstream.v1.SessionStart
	(*AgentContent)(nil),  // 4: agentstream.v1.AgentContent
	(*ToolCall)(nil),      // 5: agentstream.v1.ToolCall
	(*TypedEnvelope)(nil), // 6: agentstream.v1.TypedEnvelope
	(*anypb.Any)(nil),     // 7: google.protobuf.Any
}
var file_agentstream_proto_depIdxs = []int32{
	3, // 0: agentstream.v1.StreamEvent.session_start:type_name -> agentstream.v1.SessionStart
	4, // 1: agentstream.v1.StreamEvent.agent_content:type_name -> agentstream.v1.AgentContent
	5, // 2: agentstream.v1.StreamEvent.tool_call:type_name -> agentstream.v1.ToolCall
	7, // 3: agentstream.v1.TypedEnvelope.payload:type_name -> google.protobuf.Any
	0, // 4: agentstream.v1.AgentStream.Stream:input_type -> agentstream.v1.StreamRequest
	1, // 5: agentstream.v1.AgentStream.Chat:input_type -> agentstream.v1.ChatMessage
	0, // 6: agentstream.v1.AgentStream.StreamTyped:input_type -> agentstream.v1.StreamRequest
	2, // 7: agentstream.v1.AgentStream.Stream:output_type -> agentstream.v1.StreamEvent
	2, // 8: agentstream.v1.AgentStream.Chat:output_type -> agentstream.v1.StreamEvent
	6, // 9: agentstream.v1.AgentStream.StreamTyped:output_type -> agentstream.v1.TypedEnvelope
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agentstream_proto_init() }
func file_agentstream_proto_init() {
	if File_agentstream_proto != nil {
		return
	}
	file_agentstream_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamEvent_SessionStart)(nil),
		(*StreamEvent_AgentContent)(nil),
		(*StreamEvent_ToolCall)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentstream_proto_rawDesc), len(file_agentstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentstream_proto_goTypes,
		DependencyIndexes: file_agentstream_proto_depIdxs,
		MessageInfos:      file_agentstream_proto_msgTypes,
	}.Build()
	File_agentstream_proto = out.File
	file_agentstream_proto_goTypes = nil
	file_agentstream_proto_depIdxs = nil
}
