package grpc

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// descriptorSetFixture is generated by `just testdata-descriptorset` from
// testdata/proto/agentstream.proto — the same .proto the mock server's
// generated stubs come from, so resolving against it and against a live
// reflecting server are resolving the exact same schema.
const descriptorSetFixture = "../../../testdata/descriptorsets/agentstream.binpb"

func TestLoadDescriptorSet_ResolvesMethod(t *testing.T) {
	md, err := LoadDescriptorSet(descriptorSetFixture, "/agentstream.v1.AgentStream/Stream")
	if err != nil {
		t.Fatalf("LoadDescriptorSet: %v", err)
	}
	if md.GetName() != "Stream" {
		t.Errorf("expected method name 'Stream', got %q", md.GetName())
	}
	if !md.IsServerStreaming() {
		t.Error("expected Stream to be server-streaming")
	}
	if md.IsClientStreaming() {
		t.Error("expected Stream not to be client-streaming")
	}
	if md.GetOutputType().GetFullyQualifiedName() != "agentstream.v1.StreamEvent" {
		t.Errorf("expected output type agentstream.v1.StreamEvent, got %q", md.GetOutputType().GetFullyQualifiedName())
	}
}

func TestLoadDescriptorSet_MissingFile_ReturnsClearError(t *testing.T) {
	_, err := LoadDescriptorSet("/nonexistent/path/does-not-exist.binpb", "/agentstream.v1.AgentStream/Stream")
	if err == nil {
		t.Fatal("expected an error for a missing descriptor set file")
	}
}

func TestLoadDescriptorSet_MalformedFile_ReturnsClearError(t *testing.T) {
	path := filepath.Join(t.TempDir(), "garbage.binpb")
	if err := os.WriteFile(path, []byte("this is not a FileDescriptorSet"), 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	_, err := LoadDescriptorSet(path, "/agentstream.v1.AgentStream/Stream")
	if err == nil {
		t.Fatal("expected an error for a malformed descriptor set file")
	}
}

func TestLoadDescriptorSet_UnknownService_ReturnsClearError(t *testing.T) {
	_, err := LoadDescriptorSet(descriptorSetFixture, "/nonexistent.v1.NoSuchService/Stream")
	if err == nil {
		t.Fatal("expected an error for an unknown service")
	}
}

func TestLoadDescriptorSet_UnknownMethod_ReturnsClearError(t *testing.T) {
	_, err := LoadDescriptorSet(descriptorSetFixture, "/agentstream.v1.AgentStream/NoSuchMethod")
	if err == nil {
		t.Fatal("expected an error for an unknown method")
	}
}

// The reflection-vs-descriptor-set streaming parity check lives in
// TestTransport_AllThreeTiers_ProduceIdenticalStreamingBehavior
// (protofile_test.go), which covers this exact pair plus the .proto
// compile tier in one pass — kept there rather than duplicated here.

// TestTransport_Connect_MissingDescriptorSet_FailsBeforeDial is this
// task's other explicit Done-When: a missing descriptor-set file must
// produce a clear error before any dial attempt — Target here is
// deliberately something Connect would otherwise hang trying to reach,
// so a fast failure proves the descriptor set was checked first.
func TestTransport_Connect_MissingDescriptorSet_FailsBeforeDial(t *testing.T) {
	tr := New(Config{
		Target:            "127.0.0.1:1", // nothing listens here
		Plaintext:         true,
		Method:            "/agentstream.v1.AgentStream/Stream",
		DescriptorSetPath: "/nonexistent/path/does-not-exist.binpb",
	})

	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	err := tr.Connect(ctx)
	elapsed := time.Since(start)

	if err == nil {
		t.Fatal("expected Connect to fail for a missing descriptor set")
	}
	if elapsed > time.Second {
		t.Errorf("expected Connect to fail fast (before any dial attempt), took %v", elapsed)
	}
}
